{
  "_args": [
    [
      "chained-error@1.0.0",
      "D:\\MyProjects\\teenpatiserver"
    ]
  ],
  "_from": "chained-error@1.0.0",
  "_id": "chained-error@1.0.0",
  "_inBundle": false,
  "_integrity": "sha512-qpDTRJ+eLj5edYe93rQqB/JwLdUbOMnmtIKyEz09Z+RtSJeHGvlABuHanddNzbVcH83wBnjrUfAwFsw88wKhnA==",
  "_location": "/chained-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "chained-error@1.0.0",
    "name": "chained-error",
    "escapedName": "chained-error",
    "rawSpec": "1.0.0",
    "saveSpec": null,
    "fetchSpec": "1.0.0"
  },
  "_requiredBy": [
    "/ts-sql-query"
  ],
  "_resolved": "https://registry.npmjs.org/chained-error/-/chained-error-1.0.0.tgz",
  "_spec": "1.0.0",
  "_where": "D:\\MyProjects\\teenpatiserver",
  "author": {
    "name": "Juan Luis Paz Rojas",
    "url": "http://github.com/juanluispaz"
  },
  "bugs": {
    "url": "https://github.com/juanluispaz/chained-error/issues"
  },
  "dependencies": {},
  "description": "Zero dependencies error that allows creating a chain of errors, preserving the original cause (with TypeScript support)",
  "devDependencies": {
    "typescript": "^3.5.3"
  },
  "homepage": "https://github.com/juanluispaz/chained-error",
  "keywords": [
    "error",
    "combined error",
    "caused by",
    "nested error"
  ],
  "license": "MIT",
  "main": "dist/ChainedError.js",
  "name": "chained-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/juanluispaz/chained-error.git"
  },
  "scripts": {
    "build": "rm -Rf dist/*; tsc",
    "prepublish": "npm run build"
  },
  "types": "dist/ChainedError.d.ts",
  "version": "1.0.0"
}
